/*
 * CAPE regional crop yield forecasts page.
 *
 * config.json  - hand maintained: contact details, region narrative (summary,
 *                caveats and per-combination overrides) and the predictor table.
 * manifest.json - regenerated by CAPE_crop_yield_forecast_visualization.py on
 *                every run: one entry per region / crop / season / forecast
 *                month that has graphics on disk. The crop, season and forecast
 *                month selectors are built from it, so a new forecast month
 *                becomes selectable as soon as the manifest is committed.
 */

let config = null;
let manifest = null;
let currentRegion = null;

// The methods and references content is shared by every region, so it lives in
// its own tab rather than being repeated at the foot of each one.
const METHODS_TAB = '__methods__';

// Remembered per region so switching tabs and coming back keeps your place.
const selectionByRegion = {};

// Load configuration and the manifest of available graphics
async function loadData() {
    try {
        const configResponse = await fetch('config.json');
        config = await configResponse.json();

        const manifestResponse = await fetch(config.manifestUrl || 'manifest.json');
        manifest = await manifestResponse.json();
        initializePage();
    } catch (error) {
        console.error('Error loading data:', error);
        document.getElementById('content').innerHTML =
            '<p>Error loading configuration or forecast manifest.</p>';
    }
}

function initializePage() {
    // Header date line. The release date is editorial and set in config.json;
    // the refresh date comes from the manifest, so it tracks the graphics.
    const refreshed = (manifest.generated || '').slice(0, 10);
    document.getElementById('forecast-date').textContent =
        [config.lastUpdated ? `Released on ${config.lastUpdated}` : null,
         refreshed ? `Forecast graphics last refreshed ${refreshed}` : null,
         'Select a crop, season and forecast month below']
            .filter(Boolean).join(' | ');

    // Which version of the CAPE forecasts this page shows, with a link to the
    // parallel page for the other version (both set in config.json)
    const version = config.version || {};
    if (version.label) {
        const other = version.otherVersion;
        document.getElementById('version-info').innerHTML =
            `<span class="version-badge">${escapeHtml(version.label)}</span>` +
            (version.description ? ` ${escapeHtml(version.description)}` : '') +
            (other && other.url
                ? ` <a href="${escapeHtml(other.url)}">${escapeHtml(other.label || 'Other version')} &rarr;</a>`
                : '');
    }

    // Contact info
    document.getElementById('contact-info').innerHTML =
        `<a href="mailto:${config.contact.email1}">${config.contact.name1}</a> and ` +
        `<a href="mailto:${config.contact.email2}">${config.contact.name2}</a>`;

    // Region tabs, built from config so regions live in one place only
    const tabsNav = document.getElementById('region-tabs');
    const methodsLabel = config.methodsTabLabel || 'Methods & References';
    tabsNav.innerHTML = config.regions.map(region => `
        <button class="tab-button" data-region="${region.id}">${escapeHtml(region.name)}</button>
    `).join('') + `
        <button class="tab-button tab-methods" data-region="${METHODS_TAB}">${escapeHtml(methodsLabel)}</button>
    `;

    tabsNav.querySelectorAll('.tab-button').forEach(button => {
        button.addEventListener('click', () => switchRegion(button.dataset.region));
    });

    switchRegion(config.regions[0].id);
}

// -------------------------------------------------------------------------
// Manifest queries
// -------------------------------------------------------------------------

/*
 * Entries for a region, restricted to one model. The figure tree also carries an
 * LR model alongside GB; without this the two would appear as duplicate forecast
 * months in the selector, indistinguishable to the reader. Falls back to showing
 * everything if the preferred model has nothing for this region.
 */
function entriesForRegion(regionId) {
    const entries = manifest.entries.filter(entry => entry.regionId === regionId);
    const preferred = entries.filter(entry => entry.model === (config.model || 'GB'));
    return preferred.length > 0 ? preferred : entries;
}

function unique(values) {
    return [...new Set(values)];
}

// Newest first, by when the graphics were produced. Only used to break ties
// between different crops or seasons, where there is no common season calendar.
function byNewest(a, b) {
    return (b.updatedTs || 0) - (a.updatedTs || 0);
}

/*
 * Order a season's forecast months around the growing season rather than by
 * month number: Deyr runs November to February, and the southern Africa summer
 * season November to April, so a plain numeric sort would put February first.
 * The season starts at the month following the widest gap in the months that
 * are available, which recovers the right order without hard coding calendars.
 */
function seasonMonthOrder(months) {
    const sorted = [...new Set(months)].sort((a, b) => a - b);
    if (sorted.length < 2) return sorted;

    let startIndex = 0;
    let widestGap = -1;
    sorted.forEach((month, index) => {
        const previous = sorted[(index - 1 + sorted.length) % sorted.length];
        const gap = (month - previous + 12) % 12;
        if (gap > widestGap) {
            widestGap = gap;
            startIndex = index;
        }
    });

    return [...sorted.slice(startIndex), ...sorted.slice(0, startIndex)];
}

// Entries for one crop and season, earliest forecast month in the season first
function inSeasonOrder(entries) {
    const position = new Map(
        seasonMonthOrder(entries.map(e => e.month)).map((month, index) => [month, index])
    );
    return [...entries].sort((a, b) =>
        (a.year - b.year) || (position.get(a.month) - position.get(b.month))
    );
}

/*
 * Resolve a (possibly stale or incomplete) selection against what the manifest
 * actually has, narrowing one level at a time: crop, then season, then forecast
 * month. Anything that cannot be honoured falls back to the region default from
 * config.json, and then to the most recently produced forecast.
 */
function resolveSelection(regionId, desired) {
    const entries = entriesForRegion(regionId);
    if (entries.length === 0) return null;

    const region = config.regions.find(r => r.id === regionId) || {};
    const fallback = region.default || {};
    const newest = [...entries].sort(byNewest)[0];

    const crops = unique(entries.map(e => e.crop)).sort();
    const crop = [desired.crop, fallback.crop, newest.crop].find(c => crops.includes(c));

    const cropEntries = entries.filter(e => e.crop === crop);
    const newestForCrop = [...cropEntries].sort(byNewest)[0];
    const seasons = unique(cropEntries.map(e => e.season)).sort();
    const season = [desired.season, fallback.season, newestForCrop.season]
        .find(s => seasons.includes(s));

    // A region may pin a default forecast month in config.json; otherwise the
    // page opens on the latest forecast month in the season.
    const monthEntries = inSeasonOrder(cropEntries.filter(e => e.season === season));
    const entry =
        monthEntries.find(e => e.id === desired.entryId) ||
        monthEntries.find(e => e.monthName === fallback.month &&
            (fallback.year === undefined || e.year === fallback.year)) ||
        monthEntries[monthEntries.length - 1];

    return { crops, crop, seasons, season, monthEntries, entry };
}

// -------------------------------------------------------------------------
// Narrative text
// -------------------------------------------------------------------------

/*
 * Pick the narrative for the selected combination. A note in config.json matches
 * when every field it specifies equals the selection; fields it omits are
 * wildcards. The note specifying the most fields wins, so a note for one
 * forecast month beats a note for the whole crop.
 */
function narrativeFor(region, entry) {
    let summary = region.summary || '';
    let caveats = [...(region.caveats || [])];
    if (!entry) return { summary, caveats };

    const fields = { crop: entry.crop, season: entry.season, month: entry.monthName, year: entry.year };

    const matches = (region.notes || []).filter(note =>
        Object.keys(fields).every(key => note[key] === undefined || note[key] === fields[key])
    );
    matches.sort((a, b) =>
        Object.keys(fields).filter(k => a[k] !== undefined).length -
        Object.keys(fields).filter(k => b[k] !== undefined).length
    );

    matches.forEach(note => {
        if (note.summary) summary = note.summary;
        if (note.caveats) caveats = [...note.caveats];
        if (note.extraCaveats) caveats = [...caveats, ...note.extraCaveats];
    });

    return { summary, caveats };
}

// Minimal **bold** support, matching how the summaries are written in config.json
function renderText(text) {
    return escapeHtml(text).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
}

function escapeHtml(text) {
    return String(text)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

// -------------------------------------------------------------------------
// Rendering
// -------------------------------------------------------------------------

function switchRegion(regionId) {
    currentRegion = regionId;

    document.querySelectorAll('.tab-button').forEach(button => {
        button.classList.toggle('active', button.dataset.region === regionId);
    });

    render();
}

function render() {
    const selectorsDiv = document.getElementById('selectors');
    const contentDiv = document.getElementById('content');

    // The methods tab has no crop, season or forecast month to choose
    if (currentRegion === METHODS_TAB) {
        selectorsDiv.innerHTML = '';
        contentDiv.innerHTML = `<div class="region-content active">${getMethodsSection()}</div>`;
        return;
    }

    const region = config.regions.find(r => r.id === currentRegion);
    if (!region) return;

    const resolved = resolveSelection(currentRegion, selectionByRegion[currentRegion] || {});

    if (!resolved) {
        selectorsDiv.innerHTML = '';
        contentDiv.innerHTML = `
            <div class="region-content active">
                <div class="region-header"><h2>${escapeHtml(region.name)}</h2></div>
                <div class="coming-soon">
                    <h3>🚀 Coming Soon</h3>
                    <p>Maps and forecasts for ${escapeHtml(region.name)} will be available in future updates.</p>
                </div>
            </div>
        `;
        return;
    }

    // Remember the resolved selection so it survives a tab switch
    selectionByRegion[currentRegion] = {
        crop: resolved.crop,
        season: resolved.season,
        entryId: resolved.entry.id
    };

    renderSelectors(selectorsDiv, resolved);
    renderRegion(contentDiv, region, resolved.entry);
}

function renderSelectors(container, resolved) {
    const seasonLabels = config.seasonLabels || {};
    const { crop, crops, season, seasons, monthEntries, entry } = resolved;

    const cropOptions = crops.map(value =>
        `<option value="${escapeHtml(value)}"${value === crop ? ' selected' : ''}>${escapeHtml(value)}</option>`
    ).join('');

    const seasonOptions = seasons.map(value =>
        `<option value="${escapeHtml(value)}"${value === season ? ' selected' : ''}>${escapeHtml(seasonLabels[value] || value)}</option>`
    ).join('');

    // Already ordered earliest-in-season first by resolveSelection
    const monthOptions = monthEntries.map(item =>
        `<option value="${escapeHtml(item.id)}"${item.id === entry.id ? ' selected' : ''}>` +
        `${escapeHtml(item.monthName)} &mdash; ${item.year} harvest</option>`
    ).join('');

    const seasonNote = (config.seasonNotes || {})[season];

    container.innerHTML = `
        <div class="selector-group">
            <label for="crop-select">Crop</label>
            <select id="crop-select"${crops.length < 2 ? ' disabled' : ''}>${cropOptions}</select>
        </div>
        <div class="selector-group">
            <label for="season-select">Season</label>
            <select id="season-select"${seasons.length < 2 ? ' disabled' : ''}>${seasonOptions}</select>
        </div>
        <div class="selector-group">
            <label for="month-select">Forecast based on data through</label>
            <select id="month-select"${monthEntries.length < 2 ? ' disabled' : ''}>${monthOptions}</select>
        </div>
        ${seasonNote ? `<p class="selector-note">${escapeHtml(seasonNote)}</p>` : ''}
    `;

    // Changing the crop or season clears the narrower choices so they re-resolve
    container.querySelector('#crop-select').addEventListener('change', event => {
        selectionByRegion[currentRegion] = { crop: event.target.value };
        render();
    });
    container.querySelector('#season-select').addEventListener('change', event => {
        selectionByRegion[currentRegion] = { crop, season: event.target.value };
        render();
    });
    container.querySelector('#month-select').addEventListener('change', event => {
        selectionByRegion[currentRegion] = { crop, season, entryId: event.target.value };
        render();
    });
}

function renderRegion(container, region, entry) {
    const base = manifest.imageBase;
    const images = entry.images || {};
    const seasonLabel = (config.seasonLabels || {})[entry.season] || entry.seasonLabel || entry.season;
    const { summary, caveats } = narrativeFor(region, entry);

    let html = `
        <div class="region-content active">
            <div class="region-header">
                <h2>${escapeHtml(region.name)}</h2>
                <div class="crop-info">
                    <span><strong>Crop:</strong> ${escapeHtml(entry.crop)}</span>
                    <span><strong>Season:</strong> ${escapeHtml(seasonLabel)}</span>
                    <span><strong>Harvest year:</strong> ${entry.year}</span>
                    <span><strong>Based on data through:</strong> ${escapeHtml(entry.monthName)}</span>
                    ${entry.countries && entry.countries.length
                        ? `<span><strong>Countries:</strong> ${escapeHtml(entry.countries.join(', '))}</span>`
                        : ''}
                </div>
            </div>
    `;

    if (summary) {
        html += `<div class="summary">${renderText(summary)}</div>`;
    }

    if (caveats.length > 0) {
        html += `
            <div class="caveats">
                <h3>⚠️ Key Details and Caveats</h3>
                <ul>${caveats.map(caveat => `<li>${renderText(caveat)}</li>`).join('')}</ul>
            </div>
        `;
    }

    // Forecast maps
    html += `<div class="figures-section"><h3>Crop Yield Forecasts</h3><div class="figure-grid">`;

    if (images.absolute) {
        html += createFigure(base + images.absolute,
            'Absolute yield forecast (in mt/ha)',
            'Forecasts masked for data availability.');
    }

    // One percent-anomaly map per observed-yield baseline the run produced
    (entry.anomalies || []).forEach(anomaly => {
        const url = anomaly.percentMasked || anomaly.percent;
        if (url) {
            html += createFigure(base + url,
                `% Anomaly w.r.t ${anomaly.baselineStart}-${anomaly.baselineEnd} observed yield mean`);
        }
    });

    if (images.anomaly10yr) {
        html += createFigure(base + images.anomaly10yr,
            '% Anomaly w.r.t 10 years of historical yield forecasts');
    }

    if (images.skill) {
        html += createFigure(base + images.skill,
            'Skill evaluation',
            'MAPE shown is the average of out-of-sample and in-sample MAPE for the last three months in the growing season');
    }

    html += `</div></div>`;

    // Context and historical data
    html += `<div class="figures-section"><h3>Context and Historical Data</h3><div class="figure-grid">`;

    if (images.meanYield) {
        html += createFigure(base + images.meanYield, `Mean ${escapeHtml(entry.crop)} Yield`);
    }
    if (images.meanProduction) {
        html += createFigure(base + images.meanProduction, `Mean ${escapeHtml(entry.crop)} Production`);
    }
    if (images.observedYield) {
        html += createFigure(base + images.observedYield,
            'Availability of observed yield data and choice of baselines');
    }
    const cropArea = images.cropMask || images.cropAreaPct;
    if (cropArea) {
        html += createFigure(base + cropArea, '% Crop area');
    }

    html += `</div></div>`;

    // Downloadable per-admin tables, one per baseline
    const downloads = (entry.anomalies || [])
        .map(anomaly => ({ anomaly, url: anomaly.csvMasked || anomaly.csv }))
        .filter(item => item.url);

    if (downloads.length > 0) {
        html += `
            <div class="figures-section">
                <h3>Download</h3>
                <ul class="download-list">
                    ${downloads.map(item => `
                        <li><a href="${base + item.url}" download>
                            Per-admin yield forecast and anomaly table
                            (w.r.t ${item.anomaly.baselineStart}-${item.anomaly.baselineEnd} observed mean, CSV)
                        </a></li>
                    `).join('')}
                </ul>
            </div>
        `;
    }

    html += `
        <p class="methods-link">
            <a href="#" data-goto-methods>Methods, data sources and references &rarr;</a>
        </p>
    `;
    html += `</div>`;

    container.innerHTML = html;

    const methodsLink = container.querySelector('[data-goto-methods]');
    if (methodsLink) {
        methodsLink.addEventListener('click', event => {
            event.preventDefault();
            switchRegion(METHODS_TAB);
            window.scrollTo(0, 0);
        });
    }
}

function createFigure(imgUrl, title, caption = null) {
    return `
        <div class="figure-container">
            <img src="${imgUrl}" alt="${title}" loading="lazy"
                 onerror="this.alt='Image failed to load: ${title}'">
            <figcaption>
                <strong>${title}</strong>
                ${caption ? `<br><em>${caption}</em>` : ''}
            </figcaption>
        </div>
    `;
}

function getMethodsSection() {
    return `
        <div class="methods-section">
            <h3>Methods and Context</h3>
            
            <div class="cape-framework">
                <h4>📊 CAPE Modeling Framework</h4>
                <p><strong>In-season Machine Learning (ML) based sub-national scale crop yield forecasts</strong></p>
                <p style="margin-top: 10px; font-size: 0.9em; color: #666;">
                    <em>Pre-season → Vegetative growth period → Reproductive development period → Harvest</em>
                </p>
                
                <h4 style="margin-top: 15px;">Standard Earth Observation (EO) Data Sets:</h4>
                <ul>
                    <li><strong>Precipitation</strong> – CHIRPS (UCSB)</li>
                    <li><strong>Reference ETo</strong> – NOAA-PSL</li>
                    <li><strong>NDVI</strong> – eMODIS (USGS/EROS)</li>
                    <li><strong>Temperature</strong> – NOAA-PSL</li>
                </ul>
                
                <p style="margin-top: 10px;">
                    <strong>7 Monthly EO Predictors:</strong> Precip, Dry days, ETo, Temp., GDD, KDD, NDVI 
                    <br><em>(Accumulated over time: e.g., Oct, Oct-Nov, Oct-Dec)</em>
                </p>
                
                <p style="margin-top: 10px;">
                    <strong>Model:</strong> XGBoost Regression Tree Model
                </p>
            </div>

            <h4 style="margin-top: 20px;">CAPE Model Predictors:</h4>
            <div class="predictors-grid">
                ${config.cape_predictors.map(predictor => `
                    <div class="predictor-card">
                        <span class="sign">${predictor.sign}</span>
                        <div class="name">${predictor.name}</div>
                        <div class="description">${predictor.description}</div>
                    </div>
                `).join('')}
            </div>

            ${getReferencesSection()}
        </div>
    `;
}

// References, from the `references` list in config.json. Each entry renders as a
// citation, linked when it has a url and plain text when it does not. Every
// field except `title` is optional, so a bare title still renders cleanly.
function getReferencesSection() {
    const references = config.references || [];
    if (references.length === 0) return '';

    const filled = value => value !== undefined && String(value).trim() !== '';

    const items = references.map(reference => {
        const title = filled(reference.url)
            ? `<a href="${escapeHtml(reference.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(reference.title)}</a>`
            : escapeHtml(reference.title);

        // Join with a full stop, but do not double one the author field already
        // carries ("Lee, D. et al." is written with its own trailing period).
        let citation = [
            filled(reference.authors) ? escapeHtml(reference.authors) : null,
            title,
            filled(reference.source) ? escapeHtml(reference.source) : null
        ].filter(Boolean).reduce((accumulated, part) =>
            accumulated
                ? `${accumulated}${/[.?!]$/.test(accumulated) ? '' : '.'} ${part}`
                : part,
            '');

        if (filled(reference.year)) citation += ` (${escapeHtml(reference.year)})`;
        if (!/[.?!]$/.test(citation)) citation += '.';

        return `<li>${citation}</li>`;
    }).join('');

    return `
        <h4 style="margin-top: 25px;">References:</h4>
        <ol class="references-list">${items}</ol>
    `;
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', loadData);
